var test = [
    {
        test_id: 'gate',
        sub_test_id: 1,
        sub_test_name: 'Aerospace Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 2,
        sub_test_name: 'Biotechnology',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 3,
        sub_test_name: 'Civil Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 4,
        sub_test_name: 'Chemical Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 5,
        sub_test_name: 'Computer Science and Information Technology',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 6,
        sub_test_name: 'Electronics and Communication Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 7,
        sub_test_name: 'Electrical Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 8,
        sub_test_name: 'Instrumentation Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 9,
        sub_test_name: 'Mechanical Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 10,
        sub_test_name: 'Petroleum Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 11,
        sub_test_name: 'Production and Industrial Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'cat',
        sub_test_id: 1,
        sub_test_name:'General Aptitude',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    },
    {
        test_id: 'cat',
        sub_test_id: 2,
        sub_test_name:'Verbal Aptitude',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    },
    {
        test_id: 'cat',
        sub_test_id: 2,
        sub_test_name:'Logical Reasoning',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    },
    {
        test_id: 'cat',
        sub_test_id: 2,
        sub_test_name:'Quantitative Aptitude',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    }
];