var test = [
    {
        test_id: 'gate',
        sub_test_id: 1,
        sub_test_name: 'Computer Science & Engineering',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsax**ydsadsadsadsad',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'gate',
        sub_test_id: 2,
        sub_test_name: 'EE',
        duration: 5400,
        no_of_ques: 35,
        negative: 0.33,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: true,
        d_no_of_ques: 15,
        d_n_marks: 1.33,
        d_p_marks: 2,
        d_no_marks: 0
    },
    {
        test_id: 'aptitude',
        sub_test_id: 1,
        sub_test_name:'quant',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    },
    {
        test_id: 'aptitude',
        sub_test_id: 2,
        sub_test_name:'verbal',
        duration: 5400,
        no_of_ques: 30,
        negative: 0,
        positive: 1,
        no_answer: 0,
        rules: 'dssadsadsadsa',
        double_type: false,
        d_no_of_ques: null,
        d_n_marks: null,
        d_p_marks: null,
        d_no_marks: null
    }
];